sudo: required
dist: trusty
language: node_js
group: deprecated-2017Q2
node_js:
  - '4.2'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - 
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
- npm install -g http-server
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build
- cd dist
- http-server

script: karma start config/karma.conf.js --single-run